config/routes.rb
Rails.application.routes.draw do
  get '/signup', to: 'users#new'
  root 'static_pages#home'
  get '/home', to: 'static_pages#home'
  get '/help', to: 'static_pages#help'
  get '/about', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord

    # インスタンス変数への読み書き用アクセサを定義
    attr_accessor :remember_token

    # 保存時に小文字変換
    before_save {self.email = email.downcase}

    # Railsチュートリアルから拝借したメールアドレスの正規表現
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

    has_secure_password

    validates :name,
        presence: true,
        length: {maximum: 50}
    validates :email,
        presence: true,
        length: {maximum: 255},
        format: {with: VALID_EMAIL_REGEX},
        uniqueness: {case_sensitive: false}
    validates :password,
        presence: true,
        length: {minimum: 6},
        allow_nil: true # allow_blankとの同じエラーメッセージを発生させないかつ空文字は許さないための処置

    # 永続セッションのためにユーザー情報をDBに記憶
    def remember
        # 新たに生成したトークンで更新
        self.remember_token = User.new_token
        update_attribute(:remember_digest, User.digest(remember_token))
    end

    def authenticated?(remember_token)
        BCrypt::Password.new(remember_digest).is_password?(remember_token)
    end

    # 記憶ダイジェストの初期化
    def forget
        update_attribute(:remember_digest, nil)
    end

    class << self
        # 少ないコストの文字列のハッシュ値を返す
        def digest(string)
            cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine::cost
            BCrypt::Password.create(string, cost: cost)
        end
    
        # ランダムトークン生成
        def new_token
            # A-Z,a-z,0-9,-,_の組み合わせで計22文字の文字列を出力
            SecureRandom.urlsafe_base64
        end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # SessionsHelperのモジュール読み込み
  include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def create
    login_info = params[:session]
    user = User.find_by(email: login_info[:email].downcase)
    if user && user.authenticate(login_info[:password])
      log_in(user)
      params[:session][:remember_me] == "1" ? remember(user) : forget(user)
      redirect_to user
      flash[:success] = "Login success!!"
    else
      flash.now[:danger] = "Invalid email or password!!"
      render 'new'
    end
  end

  def destroy
    log_out
    redirect_to root_path
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end

  def contact
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController

  include Pagy::Backend

  before_action :logged_in_user, only: [:index, :edit, :update, :destroy]
  before_action :admin_user, only: :destroy

  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "Create success!!"
      redirect_to @user
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Update success!!"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def index
    @pagy, @users = pagy(User.all)
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = 'User deleted!!'
    redirect_to users_url
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def logged_in_user
    unless logged_in?
      flash[:danger] = 'Please login or sign up!!'
      redirect_to(login_url)
    end
  end

  def admin_user
    flash[:danger] = 'You do not have permission to delete'
    redirect_to(root_url) unless current_user.admin?
  end

end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  # gem pagのヘルパーメソッドを読み込み
  include Pagy::Frontend

  def full_title(page_title = '')
    base_title = 'sample app page'
    if page_title.empty?
      base_title
    else
      "#{page_title} #{base_title}"
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper

  # ログイン処理
  ## session[:user_id]にログイン時のユーザーIDを保持させておく
  def log_in(user)
    session[:user_id] = user.id
  end

  # ログイン中のユーザーオブジェクトを取得
  def current_user
    if user_id = session[:user_id]
      @current_user ||= User.find_by(id: session[:user_id])
    elsif user_id = cookies.signed[:user_id]
      user = User.find_by(id: user_id)
      if user && user.authenticated?(cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end

  # ログイン中かチェック
  def logged_in?
    !current_user.nil?
  end

  # セッション破棄
  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end

  # ログアウト処理
  def log_out
    # cookieからユーザー情報破棄
    forget(current_user)
    # セッションオブジェクトから:user_idを破棄
    session.delete(:user_id)
    # ユーザーオブジェクトをnilで初期化
    @current_user = nil
  end

  # セッションの永続化
  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
  # Grabatar画像を返却する
  def gravatar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5.hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{options[:size]}"
    image_tag(gravatar_url, alt: user.name, class: 'gravatar')
  end
end

app/views/layouts/_footer.html.slim
footer.footer
  small
    |  The 
    a[href="https://railstutorial.jp/"]
      | Ruby on Rails Tutorial
  nav
    ul
      li
        = link_to "About",   about_path
      li
        = link_to "Contact", contact_path
      li
        a[href="http://news.railstutorial.org/"]
          | News

app/views/layouts/_header.html.slim
header.navbar.navbar-fixed-top.navbar-inverse
  .container
    = link_to "sample app", root_path, id: "logo"
    nav
      ul.nav.navbar-nav.navbar-right
        li
          = link_to "Home", root_path
        li
          = link_to "Help", help_path
        
        - if logged_in?
          li
            = link_to "Users", users_path
          li.dropdown
            a href="#" class="dropdown-toggle" data-toggle="dropdown"
              | Account 
              b.caret
            ul.dropdown-menu
              li
                = link_to "Profile", current_user
              li
                = link_to "Setting", edit_user_path(current_user)
              li.divider
                li
                  = link_to "Logout", logout_path, method: :delete
        - else
          li
            = link_to "Login", login_path

app/views/layouts/_rails_default.html.slim
= csrf_meta_tags
= csp_meta_tag
= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
= javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      = full_title(yield(:title))
    = render 'layouts/rails_default'
    = render 'layouts/shim'
  body
    = render 'layouts/header'
    div.container
      - flash.each do |message_type, message|
        div class="alert alert-#{message_type}"
          = message
      = yield
    = render 'layouts/footer'
    = debug(params) if Rails.env.development?
    

app/views/shared/_error_messages.html.slim
- if model.errors.any?
    #error_explanation
        .alert.alert-danger
            | The form contains 
            = pluralize(model.errors.count, "error")
        ul
        = model.errors.full_messages.each do |msg|
            li
                = msg

app/views/static_pages/about.html.slim
- provide(:title, "about")
h1
  | StaticPages#about
p
  | Find me in app/views/static_pages/about.html.slim

app/views/static_pages/contact.html.slim
- provide(:title, "contact")
h1
  | StaticPages#contact
p
  | Find me in app/views/static_pages/contact.html.slim

app/views/static_pages/help.html.slim
- provide(:title, "help")
h1
  | StaticPages#help
p
  | Find me in app/views/static_pages/help.html.slim

app/views/static_pages/home.html.slim
- provide(:title, "home")
.center.jumbotron
  h1
    | StaticPages#home
  p
    | Find me in app/views/static_pages/home.html.slim
  = link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary"
= link_to image_tag("rails.png", alt: "Rails logo"), 'http://rubyonrails.org/'

app/views/users/_user.html.slim
li
  = gravatar_for user, size: 50
  = link_to user.name, user
  - if current_user.admin? && current_user.email != user.email
    |  | 
    = link_to 'delete', user,
      method: :delete,
      data: {confirm: 'You sure?'}

app/views/users/edit.html.slim
- provide(:title, "Edit user")
h1
  | Update your profile
div class="row"
  div class="col-md-6 col-md-offset-3"
    = form_for(@user) do |f|
      = render 'shared/error_messages', {model: @user}

      = f.label :name
      = f.text_field :name, class: 'form-control'

      = f.label :email
      = f.email_field :email, class: 'form-control'

      = f.label :password
      = f.password_field :password, class: 'form-control'

      = f.label :password_confirmation, "Confirmation"
      = f.password_field :password_confirmation, class: 'form-control'

      = f.submit "Save changes", class: "btn btn-primary"

    div class="gravatar_edit"
      = gravatar_for @user
      a href="http://gravatar.com/emails" rel="noopener" target="_blank" change
  

app/views/users/index.html.slim
- provide(:title, "All users")
h1
  | All users
== pagy_nav_bootstrap(@pagy) if 1 < @pagy.pages
ul.users
  - @users.each do |user|
    = render user
== pagy_nav_bootstrap(@pagy) if 1 < @pagy.pages

app/views/users/new.html.slim
= provide :title, 'Sign up'
h1
  | Sign up
.row
  .col-md-6.col-md-offset-3
    = render 'shared/error_messages', {model: @user}
    = form_for @user do |u|
      = u.label :name
      = u.text_field :name, class: 'form-control' 
      = u.label :email
      = u.text_field :email, class: 'form-control' 
      = u.label :password
      = u.password_field :password, class: 'form-control' 
      = u.label :password_confirmation, "Confirmation"
      = u.password_field :password_confirmation, class: 'form-control'
      = u.submit "Create my account", class: "btn btn-primary"

app/views/users/show.html.slim
div.row
  aside.col-md-4
    section.user_info
      h1
        = gravatar_for @user
        = @user.name